### PR TITLE
Automated Switching default_branch From 'master' To 'main'

### PR DESCRIPTION
**Pull request by sommersoft**
@kattni,

Here is what I worked out to automate switching default branches. Tested on three of my personal repositories/forks. Works as expected. I forgot to go back and condense the `try: git.nnn()` blocks... 😄 

Running it is like any other adabot tools: 1) activate adabot environment with secrets/creds, 2) run as `python3 -m adabot.update_default_branch`

Like I mentioned, I'm fairly certain perms may be an issue. Nothing in the API docs say anything, but I'm pretty confident that the repository branch protection settings will limit who is allowed to run this. Specifically updating the `default_branch`.

### CODE REVIEW

**Comment by tannewt** [comment]
Looks good to me. Thank you as always!

**Comment by kattni** [comment]
I will be bringing this up on Monday. I'd like to see this done next week.

**Comment by kattni** [comment]
I've moved the first library manually to `main` - the Circuit Playground library. The [Contributing to CircuitPython with Git and GitHub guide](https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github) has been updated to reference both `main` and `master`, and now includes instructions for verifying whether an Adafruit lib you're working on is moved to `main`, and moving your local clone/fork to `main`. The plan is to do a few more manually, I believe, before moving forward with automating this.

@sommersoft One thing I discussed with Scott is deleting the `master` branch so it throws an error if someone tries to push to it. This would be best because it will eliminate the potential for people to push to `master` and give folks an indicator that things have been updated. I can update the guide to include the error and what it means, and then we can point folks to the guide for updating their local whatnot. We'd need that step included here, I would say after the default branch has been updated.

**Comment by sommersoft** [comment]
> One thing I discussed with Scott is deleting the master branch so it throws an error if someone tries to push to it.
[....]
We'd need that step included here, I would say after the default branch has been updated.

Yep yep. The deletion of `master` branch on the repo is already in there, on line 87.

**Pull request closed without merging**
