### PR TITLE
Make URL comparison in circuitpython_libraries robust against .git suffix.

### PR DESCRIPTION
**Pull request by tdicola**
Add more logic to circuitpython_libraries script to handle git repository URLs which optionally end in .git values.  This should be more robust with Github's myriad of ways of generating clone URLs.

### CODE REVIEW

**Comment by tannewt** [comment]
The change looks good. It just needs a rebase first.

**Comment by tdicola** [comment]
Looks like github has a merge conflict fixing UI.  Just merged it in so it should be clean now.

**Comment by tannewt** [comment]
I don't think so. I think you need to

```shell
git fetch <remote name for adafruit>
git rebase -i <remote name for adafruit>/master
```

Whenever you start new changes, make sure you are starting from the latest state of adafruit master.

**Comment by tdicola** [comment]
Sorry I don't follow.. this change is in the bundle_lib_check branche.  I did a git pull origin bundle_lib_check and it did nothing.

**Comment by tannewt** [comment]
The PR is proposing merging commits that are in the bundle_lib_check branch but not master going back to the point where they share a common commit. The common shared commit is still set to what master was when you started to work on the last PR, not this one. ([This visualization](https://github.com/adafruit/adabot/network) could be helpful. Its scrollable.)

You can use interactive rebase (`git rebase -i origin/master`) to reapply the changes you've made onto a newer version of master to move up the common shared commit and thus remove commits from this PR. When it prompts you what to do with each commit you should delete the ones that were already merged if they show because they aren't needed for this PR.

**Comment by tdicola** [comment]
Looks like it's fine now after the merge.  Github is giving the green light to pull it in to master so feel free to grab it.  Thanks!

**Comment by tdicola** [comment]
Hrm is it some other page?  On this pull request page I see this:
screen shot 2018-01-18 at 2 54 02 pm
Looks good, want me to click merge?

**Comment by tannewt** [comment]
Ah! My merge was set to rebase. I'm worried a merge will result in duplicate commits for those between 6c06ff1 and e1c3114.

**Comment by tannewt** [comment]
Thanks for doing this! I'll always merge things from now on which will prevent further commit duplication as it happened here.

**Pull request merged**
