### PR TITLE
Bundle & PyPi Download Stats

### LINKED ISSUE #22: Script For Library Download Stats [Bundle & PyPi]
If you'd like download statistics for pypi:

https://pypistats.org/ and https://pypistats.org/api/
https://stackoverflow.com/questions/38102317/why-pypi-doesnt-show-download-stats-anymore (but see the newer answers)

Example: https://pypistats.org/packages/adafruit-blinka

Tagging @brennen @kattni @tannewt

### PR DESCRIPTION
**Pull request by sommersoft**
Fixes #22

### CODE REVIEW

**Comment by ladyada** [comment]
this is rad!

**Comment by sommersoft** [comment]
@ladyada the plan is to have this and the weekly reports push to the S3 bucket nightly. See #16.

**Comment by ladyada** [comment]
yah this would be rad -- please do add it!

**Comment by sommersoft** [comment]
tis imminent: https://travis-ci.com/sommersoft/adabot

**Comment by kattni** [comment]
Thanks for the final update!

**Pull request merged**
