### PR TITLE
Add More Tests

### PR DESCRIPTION
**Pull request by sommersoft**
Adds more tests for the following:

- Integration:
  - adabot/update_cp_org_libraries.py

- Unit:
  - adabot/lib/common_funcs.py::sanitize_url()
  - adabot/lib/common_funcs.py::get_docs_link()
  - adabot/lib/common_funcs.py::is_new_or_updated()

### CODE REVIEW

**Comment by sommersoft** [comment]
Please don't merge this yet. The `update_cp_org_libraries` tests are taking an unreasonable amount of time in Actions. 1 hour in Actions vs ~25 seconds locally. I'm going to run some research on my fork.

**Comment by dherrada** [comment]
@sommersoft As in running update_cp_org_libraries.py or just the actions for it?

**Comment by sommersoft** [comment]
> @sommersoft As in running update_cp_org_libraries.py or just the actions for it?

Specifically just the test for `update_cp_org_libraries.py` that I added here. Once it gets to [this test](https://github.com/adafruit/adabot/runs/3528273871?check_suite_focus=true#step:8:36), it takes an hour.

Locally, the entire test suite takes ~25 seconds. On my fork, the entire test suite takes ~45 seconds (exact copy of this branch [here](https://github.com/sommersoft/adabot/runs/3528240506?check_suite_focus=true)).

The long runtime may just be a one-off in this PR, having to do with the Actions container/cache/etc. I'm still trying to narrow down my confidence level on that though.

**Comment by dherrada** [comment]
@sommersoft Ah, I see. Oh and "libraries" is spelled "libraries" in a few tests.

**Comment by dherrada** [comment]
(looks like that autocorrected to the correct spelling, I replaced it with the correct incorrect spelling)

**Comment by sommersoft** [comment]
> @sommersoft Ah, I see. Oh and "libraries" is spelled "libraires" in a few tests.

I can't see anything in the code, nor in the repo differences, that would be causing the long runtime. So, maybe we use the typos as a testing point. 

We can merge this PR as-is, and I'll submit another PR with the typo corrections. Then we can see if the long runtime re-occurs or if it was a one-off.

Thoughts?

**Comment by dherrada** [comment]
@sommersoft Sure. Let me review it real quick.

**Review by dherrada — APPROVED** [review]
Looks good to me

**Comment by sommersoft** [comment]
Haha, the tests ran in 48s on the merge/push action trigger. Hopefully that answers that. 😄 

I'll have the typos PR in shortly.

**Pull request merged**
