### PR TITLE
Add piwheels stats

### PR DESCRIPTION
**Pull request by bennuttall**
Saw this mentioned here: https://github.com/piwheels/piwheels/issues/82 so thought I'd throw something together.

API reference: https://www.piwheels.org/json.html

It's half tested, half baked and not nicely formatted but hope it helps

### CODE REVIEW

**Comment by tannewt** [comment]
Thank you! Hopefully Melissa can take a look soon.

**Review by makermelissa — APPROVED** [review]
Code looks good to me. I don't really have a way to test.

**Comment by sommersoft** [comment]
I'm going to take a look at this soon. With `piwheels` having this functionality available now, there's no need to use the incomplete stats from `pypistats`. I'll try to just amend onto this PR with changes, unless a review request is desired.

Thanks @bennuttall and piwheels team for getting the API up & running!

**Review by dherrada — APPROVED** [review]
Looks good to me.

**Pull request merged**
