### PR TITLE
Added more files to be ignored by release check

### PR DESCRIPTION
**Pull request by dherrada**
This should ignore all ci-related changes

### CODE REVIEW

**Review by kattni — CHANGES_REQUESTED** [review]
Please include the following as well to be ignored:
- `*.license` files (which might take a little tweaking because they seem to be `filename.extension.license`)
- `.gitignore`
- `CODE_OF_CONDUCT.md`
- `README.rst`
- `pyproject.toml`
- `docs/`

Essentially, the only thing that should require a release is an update to the code itself, the examples, or anything involving the way it is packaged. Please make sure I didn't miss anything that doesn't fit within that context.

The docs will build latest on push events, and therefore should update without a release.

**Comment by kattni** [comment]
@dherrada For testing purposes, please use the Test Repo. Thanks!

**Comment by jepler** [comment]
If docs/ changes don't get a release, they will not appear on readthedocs when viewing the "stable" documentation.

**Comment by kattni** [comment]
@jepler Yeah, I gave a lot of thought to that. Ostensibly any updates to the documentation will happen within the library code, and therefore require a release anyway. I was back and forth on it a bit though. I'll leave the decision to you. Should we remove `/docs` from the ignore?

**Comment by tannewt** [comment]
I believe RTD usually tracks the latest version of the repo, not the release.

**Comment by jepler** [comment]
If the docs receive a substantial clarification without any code change, I think it would be good to make sure the updated docs are available as 'stable'.  I'm thinking (this was in the core, not the libs) about stuff like when dan recently clarified how cdc_uart readline() worked, lots of fine tuning of the words without any changes to how the code worked...

**Comment by kattni** [comment]
It looks like `docs` was not included anyway. So we're good.

**Review by kattni — APPROVED** [review]
Thanks for adding this! We'll see how it looks tomorrow.

**Pull request merged**
