### PR TITLE
Add weekly PyPI stats to daily report

### PR DESCRIPTION
**Pull request by tekktrik**
Adds the PyPI stats to the daily report, which it pulls from Google's BigQuery.  Passed the `pytest` cases locally.

I'll work on have this auto-push commits to the bundle next.

### CODE REVIEW

**Comment by tekktrik** [comment]
I tried to avoid the same issue of "can't use secrets" this time, so I'm hoping it doesn't fail in the CI here (at least not for that reason).

**Review by kattni — CHANGES_REQUESTED** [review]
This looks great! I have one thing to add though. We often have to explain why someone's PR from Monday doesn't show up in the report for the CP Weekly, which is generated at 3am or some such on Monday. So, right below `# The State of CircuitPython, the Libraries, and Blinka` please add the following:
```
This report contains information from the previous seven days. Any changes (PRs merged, etc.) made today are not included in this report.
```
Or something like that - feel free to make changes if you have better wording in mind.

Thank you!

**Review by kattni — APPROVED** [review]
Excellent, thank you!

**Comment by tekktrik** [comment]
Passed the other run of `pytest` so this new one should too since it's just logging changes!

**Pull request merged**
