### PR TITLE
Added disable pointless-string-statement check patch to update pylintrc files

### PR DESCRIPTION
**Pull request by dherrada**
@sommersoft @jepler Since you both have done this sort of thing in the past, do you think you might be able to look over this patch to see if it's correct? Thanks!

### CODE REVIEW

**Review by jepler — COMMENTED** [review]
Can you provide more info about why we want to disable this check?

Can you provide a link to a repo where this has been manually applied and CI passes?

**Comment by dherrada** [comment]
@jepler I disabled it in this pr (https://github.com/adafruit/Adafruit_CircuitPython_BNO055/pull/68). The reason I think we should disable it is that when it is enabled, Pylint doesn't let you use triple quote comments outside of docstrings.

Here's a discussion on the subject: https://github.com/PyCQA/pylint/issues/2864

**Comment by sommersoft** [comment]
I've been away for a while, but I'll add some thoughts on this.

It doesn't surprise me that pylint is rather rigid on non-docstring/unassigned multi-line strings. They're pretty strict in their adherence to PEP8 (GvR's Twitter post, not withstanding); `#` is the standard for comments.

I would be wary of allowing the different styles to coexist in the entire ecosystem. Even in the single file `examples/bno055_simpletest.py` referenced in the BNO055 PR, there are two methods used:
```py
# User these lines for UART
# uart = busio.UART(board.TX, board.RX)	# uart = busio.UART(board.TX, board.RX)
# sensor = adafruit_bno055.BNO055_UART(uart)	# sensor = adafruit_bno055.BNO055_UART(uart)
```
and
```py
"""
print(
    "Temperature: {} degrees C".format(temperature())
)  # Uncomment if using a Raspberry Pi
"""
```

Other than that, the patch file looks fine. A dry run would point out any issues/skipped repos.

**Comment by tannewt** [comment]
I agree with @sommersoft. We shouldn't change the lint settings. The BNO055 example should use `#` for the commented out bit. We should only use `"""` for comments that pylint agrees with.

**Comment by dherrada** [comment]
@tannewt @sommersoft Thanks for weighing in. I hadn't thought of it that way, but that definitely makes sense.

**Comment by jepler** [comment]
Thank you all for the comments.  I think we'll close this one up for now.

**Pull request closed without merging**
